ca:
  url: https://step-ca-step-certificates.default.svc.cluster.local
  # provisioner is the provisioner name and password that autocert will use
  provisioner:
    name: admin
    password: 1GtrgcDhcMgqeYFubfsMzhEFO1moDW9t
  # certs is the configmap in yaml that should contain the CA root certificate.
  certs:
    root_ca.crt: |-
      -----BEGIN CERTIFICATE-----
      MIIBwzCCAWmgAwIBAgIQA1gV811j5cPi80klhR9VBzAKBggqhkjOPQQDAjBAMRow
      GAYDVQQKExFTdGVwIENlcnRpZmljYXRlczEiMCAGA1UEAxMZU3RlcCBDZXJ0aWZp
      Y2F0ZXMgUm9vdCBDQTAeFw0yNTEyMDQwODQ2NTlaFw0zNTEyMDIwODQ2NTlaMEAx
      GjAYBgNVBAoTEVN0ZXAgQ2VydGlmaWNhdGVzMSIwIAYDVQQDExlTdGVwIENlcnRp
      ZmljYXRlcyBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5BSXqeeT
      zaTf89SZXxidetRkLG3V6bEnEdZXG/OBb5m4eU4unHI8shUES4PLKpdtpgO48QL0
      lPY80wEpfHBvD6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
      AQEwHQYDVR0OBBYEFH8N1/Oo7wKOUUYoGUpp/rANXqU1MAoGCCqGSM49BAMCA0gA
      MEUCIDva2pGMoLbd5UibuLCZ+BLTGAMXP7sed6hRPOuKe2ULAiEA7RNGbIon//Nb
      XNYG/gMQzBXfZV4iodAr7/3buti5Pe4=
      -----END CERTIFICATE-----
  # config is the configmap in yaml to use. This is currently optional only.
  config:
    defaults.json: |-
      {}
